version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_app
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net
    volumes:
      - ./backend:/app   # для live-reload при разработке

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_net
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

volumes:
  pg_data:

networks:
  app_net:
