"""init test

Revision ID: 3ff3537feeb4
Revises: 7b631df83a9f
Create Date: 2025-10-25 15:03:13.483460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff3537feeb4'
down_revision: Union[str, Sequence[str], None] = '7b631df83a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_history', 'old_value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('project_history', 'new_value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('project_history', 'change_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'realisation_probability',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('projects', 'evaluation_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'industry_manager',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'project_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'deleted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'current_status',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'done_this_period',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'next_period_plans',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('projects_organization_name_key', 'projects', type_='unique')
    op.drop_constraint('projects_payment_type_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_service_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_stage_id_fkey', 'projects', type_='foreignkey')
    op.alter_column('services', 'service_large_category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('services', 'service_large_category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key('projects_stage_id_fkey', 'projects', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key('projects_service_id_fkey', 'projects', 'services', ['service_id'], ['id'])
    op.create_foreign_key('projects_payment_type_id_fkey', 'projects', 'payment_types', ['payment_type_id'], ['id'])
    op.create_unique_constraint('projects_organization_name_key', 'projects', ['organization_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('projects', 'next_period_plans',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'done_this_period',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'current_status',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'deleted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'project_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'industry_manager',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'evaluation_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'realisation_probability',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_history', 'change_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('project_history', 'new_value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('project_history', 'old_value',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
