"""added new relations

Revision ID: d3d60e7bd9ae
Revises: 3ff3537feeb4
Create Date: 2025-10-26 10:10:08.885872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3d60e7bd9ae'
down_revision: Union[str, Sequence[str], None] = '3ff3537feeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'evaluation_status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'industry_manager',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'project_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'deleted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'current_status',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'done_this_period',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'next_period_plans',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'projects', 'payment_types', ['payment_type_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'next_period_plans',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'done_this_period',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'current_status',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'deleted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'project_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'industry_manager',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'evaluation_status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
